Numpy is a whole module dedicated towards matrix operations called `numpy.mat`

#### 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.

In [2]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### 3-D Arrays
- An Array that has 2-D arrays (matrices) as its elements is called 3-D array.
- These are often used to represent a 3<sup>rd</sup> order tensor.

In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [5]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

#### Check number of dimensions
- Numpy arrays provide the `ndim` attribute that returns an integer that tells us how many dimensions the array have.

In [6]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [7]:
a.ndim

0

In [8]:
b.ndim

1

In [9]:
c.ndim

2

In [10]:
d.ndim

3

#### Access Array Elements
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in Numpy arrays start with 0, meaning that the first element has index 0 and the second has index 1, etc.

In [11]:
arr = np.array([1,2,3,4])

In [12]:
arr[0]

1

In [13]:
arr[2]

3

In [14]:
arr[1]

2

In [15]:
arr[2] + arr[3]

7

To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.<br>
Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column

In [16]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [17]:
arr[0,1]

2

In [18]:
arr[1,4]

10

Access 3-D arrays
- To access elements from 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [19]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [20]:
arr[0,1,2]

6

The first number represents the first dimension, which contains two arrays:
`[[1,2,3],[4,5,6]]`<br>
and:
`[[7,8,9],[10,11,12]]`<br>
Since we selected `0`, we are left with the first array
`[[1,2,3],[4,5,6]]`<br>
The second number represents the second dimension, which also contains two arrays:
`[1,2,3]` and `[4,5,6]`<br>
Since we selected `1`, we are left with the second array: `[4,5,6]`<br>
The third number represents the third dimension, which contains three values
`4,5,6`.<br>
Since we selected `2`, we end up with the third value: `6`

In [21]:
arr[1,1,0]

10

#### Joining numpy arrays

##### 1-D arrays

In [22]:
arr1 = np.array([1,2,3])

In [23]:
arr2 = np.array([4,5,6])

In [24]:
arr = np.concatenate((arr1,arr2))

In [25]:
arr

array([1, 2, 3, 4, 5, 6])

##### 2-D arrays

###### along rows

In [26]:
arr1 = np.array([[1,2],[3,4]])

In [27]:
arr2 = np.array([[5,6],[7,8]])

In [28]:
arr = np.concatenate((arr1,arr2),axis=1)

In [29]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Splitting Numpy Arrays

Splitting is reverse operation of Joining. Joining merges multiple arrays into one and splitting breaks one array into multiple.<br>
We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits

In [3]:
arr = np.array([1,2,3,4,5,6])

In [6]:
np.array_split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [4]:
np.array_split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

#### Generating Random Numbers in Numpy

Numpy offers the random module to work with random numbers

In [7]:
x = np.random.randint(100)

In [8]:
x

59

##### Generate Random Float

In [9]:
x = np.random.rand()

In [11]:
x

0.4598811832373305